Repository betaflight/betaflight-tx-lua-scripts, pull requests merged in 2019-10, with the labels that each got.

#246 Added unified '.gitattributes' file.
  .gitattributes
Labels: housekeeping

#262 Added 'release' task to Makefile.
  Makefile
Labels: build system improvement

#256 Added option Arming without fix to GPS Rescue
  src/SCRIPTS/BF/LAYOUT/128x64/rescue.lua
  src/SCRIPTS/BF/LAYOUT/212x64/rescue.lua
  src/SCRIPTS/BF/LAYOUT/320x480/rescue.lua
  src/SCRIPTS/BF/LAYOUT/480x272/rescue.lua
  src/SCRIPTS/BF/PAGES/rescue.lua
Labels: needs coordination with firmware

#275 Remove killEvents() to fix EVT_VIRTUAL_DEC_REPT
  src/SCRIPTS/BF/ui.lua
Labels: rn: bugfix

#270 Layout fixes
  src/SCRIPTS/BF/LAYOUT/128x64/gpspids.lua
  src/SCRIPTS/BF/LAYOUT/128x64/pids2.lua
  src/SCRIPTS/BF/LAYOUT/128x64/pwm.lua
  src/SCRIPTS/BF/LAYOUT/128x64/rates.lua
  src/SCRIPTS/BF/LAYOUT/128x64/rx.lua
  src/SCRIPTS/BF/LAYOUT/128x64/vtx.lua
  src/SCRIPTS/BF/LAYOUT/212x64/pids2.lua
  src/SCRIPTS/BF/LAYOUT/212x64/pwm.lua
  src/SCRIPTS/BF/LAYOUT/212x64/rates.lua
  src/SCRIPTS/BF/LAYOUT/212x64/rescue.lua
  src/SCRIPTS/BF/LAYOUT/212x64/rx.lua
  src/SCRIPTS/BF/LAYOUT/212x64/vtx.lua
  src/SCRIPTS/BF/radios.lua
Labels: rebase / squash required

#276 Main menu scroll fix
  src/SCRIPTS/BF/radios.lua
  src/SCRIPTS/BF/ui.lua
Labels: rn: bugfix

#277 Update Readme.md
  README.md
Labels: documentation update

#278 Reduce peak memory use
  src/SCRIPTS/BF/ui.lua
Labels: rn: improvement
