Repository betaflight/betaflight-tx-lua-scripts, pull requests merged in 2019-12, with the labels that each got.

#291 Allow text for fields
  src/SCRIPTS/BF/PAGES/filters1.lua
  src/SCRIPTS/BF/PAGES/filters2.lua
  src/SCRIPTS/BF/PAGES/pid_advanced.lua
  src/SCRIPTS/BF/PAGES/pids2.lua
  src/SCRIPTS/BF/PAGES/pwm.lua
  src/SCRIPTS/BF/PAGES/rates.lua
  src/SCRIPTS/BF/PAGES/rescue.lua
  src/SCRIPTS/BF/PAGES/rx.lua
  src/SCRIPTS/BF/PAGES/vtx.lua
  src/SCRIPTS/BF/ui.lua
Labels: rn: improvement

#292 Unload background when not used + other minor changes
  src/SCRIPTS/BF/background.lua
  src/SCRIPTS/BF/data_init.lua
  src/SCRIPTS/BF/ui.lua
  src/SCRIPTS/TELEMETRY/bf.lua
Labels: rn: improvement

#295 Fix no telemetry blink for high res LCDs
  src/SCRIPTS/BF/radios.lua
Labels: rn: bugfix

#297 Fix TEXT_COLOR bug + other fixes
  src/SCRIPTS/BF/radios.lua
  src/SCRIPTS/BF/ui.lua
Labels: rn: bugfix

#298 Esc protocol backwards compatibility
  src/SCRIPTS/BF/PAGES/pwm.lua
Labels: rn: improvement

#300 Improve protocol detection
  src/SCRIPTS/BF/protocols.lua
Labels: rn: improvement

#299 Added FUNDING.yml.
  .github/FUNDING.yml
Labels: housekeeping
