Repository betaflight/betaflight-tx-lua-scripts, pull requests merged in 2020-05, with the labels that each got.

#334 Add motor protocol DISABLED
  src/SCRIPTS/BF/PAGES/pwm.lua
Labels: rn: improvement

#335 Remove Gyro/PID loop
  src/SCRIPTS/BF/PAGES/pwm.lua
Labels: rn: improvement

#338 Update readme
  README.md
  docs/assets/images/background_script_setup.png
Labels: documentation update

#341 Change init message
  src/SCRIPTS/BF/ui_init.lua
  src/SCRIPTS/TELEMETRY/bf.lua
Labels: rn: improvement

#344 Added requirement for SmartPort to README.
  README.md
Labels: documentation update

#347 Change gyro/pid rate increment direction
  src/SCRIPTS/BF/PAGES/pwm.lua
Labels: rn: bugfix
