Repository betaflight/betaflight-tx-lua-scripts, pull requests merged in 2020-10, with the labels that each got.

#364 Rename pids.lua
  src/SCRIPTS/FUNCTIONS/bfpids.lua
Labels: rn: improvement

#363 Allow drawing on whole display
  src/SCRIPTS/BF/ui.lua
Labels: rn: improvement

#366 Add FF Interpolate
  src/SCRIPTS/BF/PAGES/pids2.lua
Labels: rn: improvement

#367 Add Vbat Sag Compensation
  src/SCRIPTS/BF/PAGES/pid_advanced.lua
Labels: rn: improvement

#365 Rates type support
  src/SCRIPTS/BF/PAGES/rates.lua
  src/SCRIPTS/BF/RATETABLES/ACTUAL.lua
  src/SCRIPTS/BF/RATETABLES/BF.lua
  src/SCRIPTS/BF/RATETABLES/KISS.lua
  src/SCRIPTS/BF/RATETABLES/QUICK.lua
  src/SCRIPTS/BF/RATETABLES/RF.lua
  src/SCRIPTS/BF/ui.lua
Labels: rn: improvement

#368 Add Thrust Linearization
  src/SCRIPTS/BF/PAGES/pid_advanced.lua
Labels: needs coordination with firmware, rn: improvement

#369 Add version and release badges to readme
  README.md
Labels: documentation update

#370 Allow 0 anti gravity gain
  src/SCRIPTS/BF/PAGES/pid_advanced.lua
Labels: needs coordination with firmware, rn: bugfix
