Repository betaflight/betaflight-tx-lua-scripts, pull requests merged in 2020-03, with the labels that each got.

#319 Updated README.md.
  README.md
Labels: housekeeping

#318 Add vtx tables download to popup menu
  src/SCRIPTS/BF/ui.lua
  src/SCRIPTS/BF/ui_init.lua
Labels: rn: improvement

#320 Updated documentation from template repository.
  .github/issue_template.md
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
Labels: documentation update

#321 Fix "Radio not supported" message
  src/SCRIPTS/BF/protocols.lua
  src/SCRIPTS/BF/radios.lua
Labels: rn: improvement

#322 Fix vtx frequency backward compatibility
  src/SCRIPTS/BF/PAGES/vtx.lua
  src/SCRIPTS/BF/ui.lua
Labels: rn: improvement

#323 Moved non-azure-dependent build settings into YAML variables.
  azure-pipelines.yml
Labels: build system improvement

#324 Improved the Azure build.
  azure-pipelines.yml
Labels: build system improvement
