Repository betaflight/betaflight-tx-lua-scripts, pull requests merged in 2020-04, with the labels that each got.

#326 Update I Term Relax Cutoff max
  src/SCRIPTS/BF/PAGES/pid_advanced.lua
Labels: rn: bugfix

#331 Fixed pull request template.
  .github/pull_request_template.md
Labels: documentation update

#332 Add Dynamic Idle
  src/SCRIPTS/BF/PAGES/pid_advanced.lua
Labels: rn: improvement

#333 Dynamic idle and rpm harmonics reboot
  src/SCRIPTS/BF/PAGES/filters2.lua
  src/SCRIPTS/BF/PAGES/pid_advanced.lua
Labels: rn: improvement
