Repository betaflight/betaflight-tx-lua-scripts, pull requests merged in 2022-09, with the labels that each got.

#419 Ghost MSP support
  src/SCRIPTS/BF/MSP/ghst.lua
  src/SCRIPTS/BF/protocols.lua
Labels: needs coordination with firmware, RN: IMPROVEMENT

#429 Read lua buffer until empty
  src/SCRIPTS/BF/MSP/common.lua
  src/SCRIPTS/BF/MSP/crsf.lua
  src/SCRIPTS/BF/MSP/ghst.lua
  src/SCRIPTS/BF/MSP/sp.lua
Labels: RN: IMPROVEMENT

#447 Remove gyro/pid rate for BF 4.2
  src/SCRIPTS/BF/PAGES/pwm.lua
  src/SCRIPTS/BF/ui_init.lua
Labels: RN: BUGFIX
