Repository betaflight/betaflight-tx-lua-scripts, pull requests merged in 2022-10, with the labels that each got.

#451 Fix api version calculation
  src/SCRIPTS/BF/PAGES/failsafe.lua
  src/SCRIPTS/BF/PAGES/filters1.lua
  src/SCRIPTS/BF/PAGES/filters2.lua
  src/SCRIPTS/BF/PAGES/gpspids.lua
  src/SCRIPTS/BF/PAGES/pid_advanced.lua
  src/SCRIPTS/BF/PAGES/pids1.lua
  src/SCRIPTS/BF/PAGES/pids2.lua
  src/SCRIPTS/BF/PAGES/pwm.lua
  src/SCRIPTS/BF/PAGES/rates.lua
  src/SCRIPTS/BF/PAGES/rescue.lua
  src/SCRIPTS/BF/PAGES/rx.lua
  src/SCRIPTS/BF/PAGES/vtx.lua
  src/SCRIPTS/BF/api_version.lua
  src/SCRIPTS/BF/background.lua
  src/SCRIPTS/BF/board_info.lua
  src/SCRIPTS/BF/pages.lua
  src/SCRIPTS/BF/rtc.lua
  src/SCRIPTS/BF/ui.lua
  src/SCRIPTS/BF/ui_init.lua
Labels: RN: BUGFIX

#452 Increase dynamic idle limit
  src/SCRIPTS/BF/PAGES/pid_advanced.lua
Labels: RN: IMPROVEMENT

#453 Update anti gravity
  src/SCRIPTS/BF/PAGES/pid_advanced.lua
Labels: RN: IMPROVEMENT

#454 Change anti gravity gain scale
  src/SCRIPTS/BF/PAGES/pid_advanced.lua
Labels: RN: IMPROVEMENT

#446 Update PID Profile
  src/SCRIPTS/BF/PAGES/pid_advanced.lua
  src/SCRIPTS/BF/PAGES/rates.lua
Labels: needs coordination with firmware, RN: IMPROVEMENT
