Repository betaflight/betaflight-tx-lua-scripts, pull requests merged in 2024-03, with the labels that each got.

#500 Download board info only if necessary
  src/SCRIPTS/BF/CONFIRM/pwm.lua
  src/SCRIPTS/BF/PAGES/INIT/pwm.lua
  src/SCRIPTS/BF/pages.lua
  src/SCRIPTS/BF/ui.lua
  src/SCRIPTS/BF/ui_init.lua
Labels: RN: IMPROVEMENT

#502 Release assets upload fix
  .github/workflows/build-release.yml
Labels: housekeeping

#496 Hide OSD (SD) settings
  src/SCRIPTS/BF/PAGES/pos_osd.lua
  src/SCRIPTS/BF/features.lua
  src/SCRIPTS/BF/features_info.lua
  src/SCRIPTS/BF/pages.lua
Labels: pinned, RN: IMPROVEMENT
